/*
Problem: Find the Difference
Problem No: 389
Platform: LeetCode
Difficulty: Easy
Topics: String, Bit Manipulation
Language: Java

----------------------------------
Problem Statement:
----------------------------------
You are given two strings s and t.
String t is generated by shuffling s and adding one extra character.

Return the character that was added.

----------------------------------
Approach:
----------------------------------
1. Use XOR operation.
2. XOR all characters of string s and t.
3. Since same characters cancel out, the remaining value
   will be the extra character.

----------------------------------
Time Complexity: O(n)
Space Complexity: O(1)

----------------------------------
Solution:
----------------------------------
*/

class Solution {
    public char findTheDifference(String s, String t) {
        char result = 0;

        for (char c : s.toCharArray()) {
            result ^= c;
        }

        for (char c : t.toCharArray()) {
            result ^= c;
        }

        return result;
    }
}
